/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "action.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Transfer, Transfer, AUTO)

PB_BIND(Execution, Execution, AUTO)

PB_BIND(ActionCore, ActionCore, AUTO)

PB_BIND(Action, Action, AUTO)
