/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_BLOCKCHAIN_PB_H_INCLUDED
#define PB_BLOCKCHAIN_PB_H_INCLUDED
#include "action.pb.h"
#include "timestamp.pb.h"
#include <extern/nanopb/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Account Metadata */
typedef struct _AccountMeta
{
	pb_callback_t address;
	pb_callback_t balance;
	uint64_t nonce;
	uint64_t pendingNonce;
	uint64_t numActions;
	bool isContract;
} AccountMeta;

#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define AccountMeta_init_default                                                                   \
	{                                                                                              \
		{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0                                                 \
	}
#define AccountMeta_init_zero                                                                      \
	{                                                                                              \
		{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0                                                 \
	}

/* Field tags (for use in manual encoding/decoding) */
#define AccountMeta_address_tag 1
#define AccountMeta_balance_tag 2
#define AccountMeta_nonce_tag 3
#define AccountMeta_pendingNonce_tag 4
#define AccountMeta_numActions_tag 5
#define AccountMeta_isContract_tag 6

/* Struct field encoding specification for nanopb */
#define AccountMeta_FIELDLIST(X, a)                                                                \
	X(a, CALLBACK, SINGULAR, STRING, address, 1)                                                   \
	X(a, CALLBACK, SINGULAR, STRING, balance, 2)                                                   \
	X(a, STATIC, SINGULAR, UINT64, nonce, 3)                                                       \
	X(a, STATIC, SINGULAR, UINT64, pendingNonce, 4)                                                \
	X(a, STATIC, SINGULAR, UINT64, numActions, 5)                                                  \
	X(a, STATIC, SINGULAR, BOOL, isContract, 6)
#define AccountMeta_CALLBACK pb_default_field_callback
#define AccountMeta_DEFAULT NULL

	extern const pb_msgdesc_t AccountMeta_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AccountMeta_fields &AccountMeta_msg

	/* Maximum encoded size of messages (where known) */
	/* AccountMeta_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
